export interface ClientTicket {
  clientId: string,
  maDatCho: string,
  maXuatVe: string,
  soTien: number,
  tinhTrangVe: string,
  hangBay: string,
  sanBayDi_chieuDi: string,
  sanBayDen_chieuDi: string,
  sanBayDi_chieuVe: string,
  sanBayDen_chieuVe: string,
  gioBay_chieuDi: string,
  gioDen_chieuDi: string,
  gioBay_chieuVe: string,
  gioDen_chieuVe: string,
  ngayBay_chieuDi: string,
  ngayDen_chieuDi: string,
  ngayBay_chieuVe: string,
  ngayDen_chieuVe: string,
  id: string,
  createdAt: string,
  updatedAt: string
}