export const emailRequest = "songnghia.uit1@gmail.com"
export const emailApprove = "songnghia.uit2@gmail.com"
// export const emailRequest = "quylk2906@gmail.com"
// export const emailApprove = "quylk2906@gmail.com"
export const hostingEmail = "lkquyit@gmail.com"
